### ISSUE TITLE
an issue about the way to compute k-th hop attention score

### ISSUE THREAD

**Issue by huafeihuang** [null-xyj/CoBFormer#2]
您好，我最近拜读了这个工作的论文和代码，对于其中的Attn-k分数计算方式感兴趣，想问请教几个问题：
（1）这个分数是根据全局attention，即形状为[N, N]的注意力矩阵计算的吗，还是根据torch_geometric框架，形状为[E,](边数)得到的呢。
（2）还有就是k阶的邻居是怎么得到的呢，我用邻接矩阵的方式试了几个数据集后，发现如果用A^k的方式，当k>6之后，很快就成为了完全图。
如果作者有其他实现方式，我希望可以了解一下attn-k的实现方式。

**Comment by null-xyj** [comment]
您好，感谢您对我们工作的关注：

1. 注意力分数是通过 [N,N] 的注意力矩阵计算的；
2. 求解k阶邻居可以通过邻接矩阵相乘的方式求解，伪代码如下：
```
A = A + I // add self loop
A_k = I // k hop neighbors
D_k = A_k  // k-th hop neighbors
for i in range(K+1):
    B_k = BOOL(A_k * A) // calculate (k+1) hop neighbours
    D_k = B_k - A_k // calculate (k+1)-th hop neighbours
    A_k = B_k // update A_k
```
希望会对你有帮助！

**Comment by null-xyj** [comment]
> 您好，感谢您对我们工作的关注：
> 
> 1. 注意力分数是通过 [N,N] 的注意力矩阵计算的；
> 2. 求解k阶邻居可以通过邻接矩阵相乘的方式求解，伪代码如下：
> 
> ```
> A = A + I // add self loop
> A_k = I // k hop neighbors
> D_k = A_k  // k-th hop neighbors
> for i in range(K+1):
>     B_k = BOOL(A_k * A) // calculate (k+1) hop neighbours
>     D_k = B_k - A_k // calculate (k+1)-th hop neighbours
>     A_k = B_k // update A_k
> ```
> 
> 希望会对你有帮助！

您好，感谢您对我们工作的关注：

注意力分数是通过 [N,N] 的注意力矩阵计算的；
求解k阶邻居可以通过邻接矩阵相乘的方式求解，伪代码如下：
```
A = A + I // add self loop
A_k = I // init k hop neighbors matrix
D_k = A_k  // init k-th hop neighbors matrix
for k in range(K+1):
    B_k = BOOL(A_k * A) // calculate (k+1) hop neighbours
    D_k = B_k - A_k // calculate (k+1)-th hop neighbours
    A_k = B_k // update A_k
```
希望会对你有帮助！

**Comment by null-xyj** [comment]
> 您好，我最近拜读了这个工作的论文和代码，对于其中的Attn-k分数计算方式感兴趣，想问请教几个问题： （1）这个分数是根据全局attention，即形状为[N, N]的注意力矩阵计算的吗，还是根据torch_geometric框架，形状为[E,](%E8%BE%B9%E6%95%B0)得到的呢。 （2）还有就是k阶的邻居是怎么得到的呢，我用邻接矩阵的方式试了几个数据集后，发现如果用A^k的方式，当k>6之后，很快就成为了完全图。 如果作者有其他实现方式，我希望可以了解一下attn-k的实现方式。

您好，感谢您对我们工作的关注：

注意力分数是通过 [N,N] 的注意力矩阵计算的；
求解k阶邻居可以通过邻接矩阵相乘的方式求解，伪代码如下：

```
A = A + I // add self loop
A_k = I // init k hop neighbors matrix
D_k = A_k  // init k-th hop neighbors matrix
for k in range(K+1):
    B_k = BOOL(A_k * A) // calculate (k+1) hop neighbours
    D_k = B_k - A_k // calculate (k+1)-th hop neighbours
    A_k = B_k // update A_k
```
希望会对你有帮助！

**Comment by huafeihuang** [comment]
谢谢您的解答！我已经根据这个实现了论文图中的attn-k效果。: )
