### ISSUE TITLE
Comparsion with SGFormer

### ISSUE THREAD

**Issue by hmtbgc** [null-xyj/CoBFormer#3]
Thanks for your excellent work. I am curious about experimental setting of SGFormer and your model, since the accuracy reported in this paper is lower than the original paper.
![image](https://github.com/null-xyj/CoBFormer/assets/32740258/16551ebb-c0e9-4029-8475-d72a6601145a)
<img width="778" alt="test" src="https://github.com/null-xyj/CoBFormer/assets/32740258/e8978c2c-5803-487d-9439-154c21f82212">

**Comment by null-xyj** [comment]
> Thanks for your excellent work. I am curious about experimental setting of SGFormer and your model, since the accuracy reported in this paper is lower than the original paper. ![image](https://private-user-images.githubusercontent.com/32740258/344416620-16551ebb-c0e9-4029-8475-d72a6601145a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2ODExMDIsIm5iZiI6MTcxOTY4MDgwMiwicGF0aCI6Ii8zMjc0MDI1OC8zNDQ0MTY2MjAtMTY1NTFlYmItYzBlOS00MDI5LTg0NzUtZDcyYTY2MDExNDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDE3MDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhOTUzYzJkY2RhMmE4MDZjNGMxYWY2ZGQ5MGNmZjk3ZjVlMWZjNTU1Njg5MGQzNzc3OGM4NzJmMjFlNTI1YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4oyQi_LkwOibnR8icS2EcNsnKV_M3IeUiy36_RImHlo) <img alt="test" width="778" src="https://private-user-images.githubusercontent.com/32740258/344416721-e8978c2c-5803-487d-9439-154c21f82212.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2ODExMDIsIm5iZiI6MTcxOTY4MDgwMiwicGF0aCI6Ii8zMjc0MDI1OC8zNDQ0MTY3MjEtZTg5NzhjMmMtNTgwMy00ODdkLTk0MzktMTU0YzIxZjgyMjEyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDE3MDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MmU4NWQxNTRiZjUzNDdiYzExNGM1NjU4Y2QwNjkyZDNhYzYzOTk4NmExNGIxY2U5Yzg0Y2FkNzkwOTM1OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xLISvu3HLrV171sJ8CxHGjHxSAt1asWVs8mIC0ugxHw">

SGFormer achieves relatively high accuracy by randomly selecting 20 nodes per class for the training set. However, we adopt the public split provided by PyG, which is a more challenging setting widely used for comparing node classification performance across models. Interestingly, under the random selection of 20 nodes per class, our model can achieve over 86% node classification accuracy on the Cora dataset.
