### ISSUE TITLE
How to compute k-th hop attention score

### ISSUE THREAD

**Issue by hzlhzlhzlhzl** [null-xyj/CoBFormer#4]
您好，感谢您的工作，对于其中的Attn-k分数计算方式感兴趣，想问请教一个问题：
1、在得到k-th邻接矩阵（E,E）后，是计算Atten矩阵（E,E）对应位置的平均值吗？
2、Nodeformer中的注意力还是按照softmax(QK/h)得到，还是会根据核方法调整计算方式？
我希望可以了解一下attn-k的实现方式。

**Comment by null-xyj** [comment]
> 您好，感谢您的工作，对于其中的Attn-k分数计算方式感兴趣，想问请教一个问题： 1、在得到k-th邻接矩阵（E,E）后，是计算Atten矩阵（E,E）对应位置的平均值吗？ 2、Nodeformer中的注意力还是按照softmax(QK/h)得到，还是会根据核方法调整计算方式？ 我希望可以了解一下attn-k的实现方式。

感谢您对我们工作的关注！Attn-k 的计算方式可以参考我们在文中给出的公式（3）.具体来说：
1. 我们计算每个节点分配给第k跳邻居的注意力分数之和的平均值，反应的是节点对第 k 跳邻居的整体关注程度；
2. Nodeformer 采用核函数计算注意力，我们并不采用 Softmax(QK/h) 计算其注意力，而是根据其文中的公式 (6,7,12)进行计算。
